Repository virtual-kubelet/azure-aci, pull requests merged in 2022-09, with the labels that each got.

#281 chore: Add go sdk dependency and apply it for aci volume
  client/aci/types.go
  go.mod
  go.sum
  provider/aci.go
  provider/aci_test.go
Labels: enhancement

#284 fix: Use distroless instead of scratch in dockerfile
  Dockerfile
  Makefile
Labels: bug

#288 ci: Remove dash from cluster name
  .github/workflows/e2e-tests.yml
Labels: ci

#286 fix: add azure dns to request object
  client/aci/client_test.go
  provider/aci.go
Labels: bug

#290 ci: Update SemVer
  .github/workflows/chart.yml
  .github/workflows/create-release.yml
  .github/workflows/lint.yml
  .github/workflows/publish-images.yml
Labels: ci

#296 chore: bump go to 1.18 and chart to v1.4.4
  .github/workflows/lint.yml
  Dockerfile
  Makefile
  charts/virtual-kubelet/Chart.yaml
  charts/virtual-kubelet/README.md
  charts/virtual-kubelet/values.yaml
  go.mod
  go.sum
Labels: chore

#298 chore: Upgrade workflows to go 1.18
  .github/workflows/e2e-tests.yml
  .github/workflows/tests.yml
Labels: chore

#299 chore: Use Azure SDK for auth
  charts/virtual-kubelet/templates/deployment.yaml
  go.mod
  go.sum
  pkg/auth/auth.go
  pkg/auth/auth_test.go
  provider/aci.go
Labels: chore

#300 chore: Migrate ACI log analytics to use Azure SDK
  pkg/analytics/analytics.go
  pkg/analytics/analytics_test.go
Labels: chore

#304 doc: Downgrade readme
  docs/DOWNGRADE-README.md
Labels: documentation

#306 doc: Update the downgrade branch to be the release tag
  docs/DOWNGRADE-README.md
Labels: documentation

#305 fix: Fix multi-volume issue
  e2e/fixtures/csi-driver.yml
  e2e/fixtures/multi-volume.yml
  e2e/volume_test.go
  go.mod
  provider/aci.go
  provider/aci_test.go
  provider/aci_volumes_test.go
Labels: bug

#312 Remove pull_request check in checkout step
  .github/workflows/tests.yml
Labels: ci
