Repository virtual-kubelet/azure-aci, pull requests merged in 2022-10, with the labels that each got.

#301 chore: Migrate to use Azure SDK clients
  client/aci/client_test.go
  pkg/client/client.go
  pkg/client/client_apis.go
  pkg/client/extensions.go
  pkg/client/interfaces.go
  pkg/client/retry.go
  pkg/types.go
Labels: chore

#316 chore: ACI mocks
  pkg/provider/aksCredential.go
  pkg/provider/docker_config.go
  pkg/provider/docker_config_test.go
  pkg/provider/example.toml
  pkg/provider/mock_aci_test.go
  pkg/provider/mocks_k8s_listers_test.go
  pkg/provider/podsTracker.go
Labels: chore

#320 chore: Bump helm chart version
  charts/virtual-kubelet/Chart.yaml
  charts/virtual-kubelet/README.md
  charts/virtual-kubelet/values.yaml
Labels: helm, chore

#315 chore: Migrate metrics
  go.mod
  pkg/client/client.go
  pkg/client/client_apis.go
  pkg/client/interfaces.go
  pkg/client/metrics_client.go
  pkg/metrics/cache.go
  pkg/metrics/container_insights.go
  pkg/metrics/container_insights_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/mock_metrics_test.go
  pkg/metrics/real_time.go
  pkg/provider/mock_aci_test.go
  pkg/types.go
Labels: chore

#322 doc: Update downgrade document with SP
  docs/DOWNGRADE-README.md
Labels: documentation

#323 chore: Move config to new folder
  pkg/provider/config.go
  pkg/provider/config_test.go
Labels: chore

#278 chore: Use correct make deps for bin/% target
  Makefile
Labels: enhancement, ci

#279 ci: Use built-in duplicate detection
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: enhancement, ci

#324 ci: Add CodeQL workflow
  .github/workflows/codeql.yml
  CODEOWNERS
  OWNERS
Labels: ci

#325 doc: Add Contributing and CoC doc
  CODETRIBUTING.md
  CODE_OF_CONDUCT.md
Labels: documentation

#327 Update Github templates
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_issue.md
Labels: chore

#326 chore: Implement MarshalJSON for containerGroupproperties wrapper
  .github/workflows/lint.yml
  pkg/client/client.go
  pkg/client/extensions.go
Labels: chore

#317 chore: Update azure aci provider to use SDK
  pkg/provider/aci.go
  pkg/provider/aci_test.go
  pkg/provider/aci_volumes_test.go
Labels: chore

#331 chore: Add dependency between workflows and fix UR issue
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  pkg/provider/aci.go
  pkg/provider/aci_test.go
Labels: ci

#332 ci: Enhance CI and Dockerfile
  .github/workflows/e2e-tests.yml
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: ci, chore

#333 doc: Add badges and update volume support
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  README.md
Labels: documentation

#334 fix: Add explicit name for the CG properties wrapper to fix json issue
  pkg/client/client.go
  pkg/provider/aci.go
  pkg/provider/aci_test.go
  pkg/provider/aci_volumes_test.go
Labels: bug

#318 chore: Switch main.go to use V2(SDK migration)
  .github/workflows/tests.yml
  Makefile
  charts/virtual-kubelet/templates/deployment.yaml
  charts/virtual-kubelet/values.yaml
  cmd/virtual-kubelet/main.go
  go.mod
  go.sum
  pkg/client/client_apis.go
  pkg/client/metrics_client.go
  pkg/provider/aci.go
  pkg/provider/aci_test.go
Labels: chore

#336 ci: Add image scan, pr title and markdown link checks workflows
  .github/PR_TEMPLATE.md
  .github/markdown-links-config.json
  .github/pr-title-config.json
  .github/workflows/create-release.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/pr-title-lint.yml
  README.md
Labels: ci

#335 chore: Cleanup unused files
  .github/workflows/tests.yml
  .gitignore
  README.md
  charts/virtual-kubelet-1.2.1.3.tgz
  charts/virtual-kubelet-1.3.0.tgz
  charts/virtual-kubelet-1.3.1.tgz
  charts/virtual-kubelet-1.3.2.tgz
  charts/virtual-kubelet-1.3.3.tgz
  charts/virtual-kubelet-1.3.5.tgz
  charts/virtual-kubelet-1.3.6.tgz
  charts/virtual-kubelet-1.4.0.tgz
  charts/virtual-kubelet-1.4.2.tgz
  charts/virtual-kubelet-latest.tgz
  hack/ibabou/yamlSerializer.go
Labels: chore

#337 chore: Run chart workflow only with release
  .github/workflows/chart.yml
Labels: ci

#339 chore: Retire container insights metrics
  charts/virtual-kubelet/README.md
  charts/virtual-kubelet/templates/deployment.yaml
  charts/virtual-kubelet/values.yaml
  pkg/client/client_apis.go
  pkg/client/interfaces.go
  pkg/client/metrics_client.go
  pkg/metrics/container_insights.go
  pkg/metrics/container_insights_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/mock_metrics_test.go
  pkg/provider/aci.go
  pkg/provider/aci_test.go
  pkg/provider/mock_aci_test.go
  provider/aci_test.go
  provider/config.go
Labels: chore

#340 chore: Fixate the azure SDK version
  go.mod
  go.sum
Labels: chore

#341 test: Add more UT for logAnalytics
  pkg/analytics/analytics.go
  pkg/analytics/analytics_test.go
Labels: test

#345 ci: Fix amd goarm issue
  .github/workflows/create-release.yml
  goreleaser.yml
Labels: ci
