Repository virtual-kubelet/azure-aci, pull requests merged in 2022-11, with the labels that each got.

#353 fix: Fix duplicate container ports
  pkg/provider/aci_test.go
Labels: bug

#355 chore: Split code to small func based files
  pkg/provider/aci.go
  pkg/provider/aci_test.go
  pkg/provider/aci_utils.go
  pkg/provider/aci_volumes.go
  pkg/provider/aci_volumes_test.go
  pkg/provider/containergroup_to_pod.go
  pkg/provider/vk_node.go
Labels: chore

#356 fix: Duplicate Container port fix
  e2e/fixtures/hpa.yml
  pkg/provider/aci.go
  pkg/provider/aci_test.go
Labels: bug

#357 fix: Remove all but the coreDNS ip from resolv.conf
  charts/virtual-kubelet/values.yaml
  pkg/provider/aci.go
  pkg/provider/aci_network.go
Labels: bug

#362 fix: Fix go routine issue when create a node
  cmd/virtual-kubelet/main.go
Labels: bug

#364 docs: Update downgrade document
  docs/DOWNGRADE-README.md
Labels: documentation

#363 fix: Fix pod status migration
  client/aci/client_test.go
  e2e/pods_test.go
  e2e/volume_test.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/provider/aci.go
  pkg/provider/aci_network.go
  pkg/provider/aci_test.go
  pkg/provider/aci_utils.go
  pkg/provider/aci_utils_test.go
  pkg/provider/aci_volumes_test.go
  pkg/provider/containergroup_to_pod.go
  pkg/provider/containergroup_to_pod_test.go
  pkg/provider/podsTracker.go
  pkg/tests/utils.go
Labels: bug

#365 chore: Add nil checks and traces
  pkg/client/client.go
  pkg/client/client_apis.go
  pkg/provider/aci.go
  pkg/provider/containergroup_to_pod.go
  pkg/provider/mock_aci_test.go
  pkg/validation/validator.go
Labels: chore

#367 fix: Use errdefs for not found error
  pkg/client/client_apis.go
Labels: bug

#368 chore: handle create status
  pkg/client/client.go
Labels: chore

#369 fix: update listLogs call and add e2e tests
  e2e/pods_test.go
  pkg/client/client_apis.go
Labels: bug, test

#370 security: CVE-2022-32149 fix
  go.mod
  go.sum
Labels: security

#371 chore: Update helm chart tag
  charts/virtual-kubelet/Chart.yaml
  charts/virtual-kubelet/README.md
  charts/virtual-kubelet/values.yaml
  docs/DOWNGRADE-README.md
Labels: chore

#204 feat: InitContainer support for ACI Connector
  README.md
  e2e/fixtures/initcontainers_ordertest_pod.yml
  e2e/initcontainer_test.go
  e2e/pods_test.go
  hack/e2e/aks.sh
  pkg/provider/aci.go
  pkg/provider/aci_init_container_test.go
  pkg/provider/aci_volumes_test.go
Labels: kind/feature, lgtm
