Repository virtual-kubelet/azure-aci, pull requests merged in 2023-03, with the labels that each got.

#476 fix: Use GetCG to retrieve InstanceView info
  go.mod
  go.sum
  pkg/client/client_apis.go
  pkg/featureflag/feature_flag.go
  pkg/provider/aci.go
  pkg/provider/aci_confidential_test.go
  pkg/provider/aci_test.go
  pkg/provider/containergroup_to_pod.go
  pkg/validation/validator.go
Labels: kind/bug, kind/chore

#486 chore: Upgrade go to 1.19
  .github/workflows/aks-addon-tests.yml
  .github/workflows/create-release-pull-request.yml
  .github/workflows/create-release.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  docker/init-container/Dockerfile
  docker/virtual-kubelet/Dockerfile
  go.mod
  pkg/provider/aci_test.go
Labels: kind/chore

#411 refactor: Update azure-aci to use nodeutil instead of node-cli
  cmd/init-container/main.go
  cmd/virtual-kubelet/main.go
  cmd/virtual-kubelet/ocagent.go
  go.mod
  go.sum
  pkg/metrics/cache.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/mock_metrics_test.go
  pkg/provider/aci.go
  pkg/provider/aci_confidential_test.go
  pkg/provider/aci_init_container_test.go
  pkg/provider/aci_test.go
  pkg/provider/aci_volumes.go
  pkg/provider/aci_volumes_test.go
  pkg/provider/config.go
  pkg/provider/containergroup_to_pod.go
  pkg/provider/containergroup_to_pod_test.go
  pkg/provider/podsTracker.go
  pkg/tests/utils.go
Labels: kind/refactor

#479 feat: report both old and new styles of node OS information
  pkg/provider/vk_node.go
Labels: kind/enhancement

#490 test: Update unit test target for local development
  .github/workflows/e2e-tests.yml
  .github/workflows/tests.yml
  Makefile
  hack/ci/create_aks_credentials.sh
  hack/ci/create_credentials.sh
  hack/ci/create_loganalytics_auth.sh
Labels: ci, kind/test

#492 docs: Update Readme file
  Makefile
  README.md
Labels: kind/documentation

#493 chore: Remove unused files
  pkg/provider/aksCredential.go
  pkg/provider/example.toml
Labels: kind/chore

#497 test: unit test for filterWindowsServiceAccountSecretVolume
  pkg/provider/aci_test.go
Labels: kind/test

#506 test: added unit test for deleteContainerGroup
  pkg/provider/aci_test.go
  pkg/tests/utils.go
Labels: kind/test

#505 test: Add Unit Test for GetVolumes (ProjectedVolume) with source secret
  pkg/provider/aci_volumes_test.go
Labels: kind/test

#508 test: added unit test for getPodStatus
  pkg/provider/aci_test.go
Labels: kind/test
