Repository virtual-kubelet/azure-aci, pull requests merged in 2023-02, with the labels that each got.

#440 test: Pass k8s version as variable to e2e scripts
  Makefile
  hack/e2e/aks-addon.sh
  hack/e2e/aks.sh
Labels: kind/test

#437 feat: Confidential compute changes - 2022-10-01-preview
  e2e/confidential_container_test.go
  e2e/fixtures/confidential_container_pod.yml
  hack/e2e/aks-addon.sh
  hack/e2e/aks.sh
  pkg/featureflag/feature_flag.go
  pkg/featureflag/feature_flag_test.go
  pkg/provider/aci.go
  pkg/provider/aci_confidential_test.go
Labels: kind/feature

#441 ci: Update helm e2e pipeline to run with any helm change
  .github/workflows/e2e-tests.yml
  Makefile
  hack/ci/check_mods.sh
Labels: ci

#443 ci: Run helm e2e test pipeline with PR changes
  .github/workflows/aks-addon-tests.yml
  .github/workflows/e2e-tests.yml
  Makefile
Labels: ci

#452 security: fix CVE-2022-28948
  go.mod
  go.sum
Labels: kind/security
